### ISSUE TITLE
Page: Checklist de congrès

### ISSUE THREAD

**Issue by alanlecart** [La-CHATTE-2-0/code-amienois#35]
Adapter celle de Nico avec sauvegarde de ce qui est coché avec localStorage

Modèle à reproduire:
https://docs.google.com/document/d/11j1nWXdzhHAeEUU_qS6841Q4wBy9zJ9EEwU4Exw7zrE/edit?usp=sharing

Techno à utiliser:
https://getbootstrap.com/docs/5.0/forms/checks-radios/
https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage

**Comment by chdesplancke** [comment]
Plusieurs questions : 

On devra utiliser le localStorage afin de garder les etats des checkbox pour que ça puisse être repris plus tard ? 
Le texte risque de faire assez lourd, je propose d'ajouter une icone à côté de l'élément qui ouvre une modal avec l'explication. Exemple : 

![image](https://user-images.githubusercontent.com/9298634/229744955-28a5f117-1f3f-4541-9444-91d0c7039da9.png)

**Comment by alanlecart** [comment]
Oui au chargement de la page, on chargera les données depuis le localStorage, et avec un système d'id cocher les cases à cocher. A chaque interraction avec une checkbox, le localstorage sera mis à jour (sauvegarder true/false, ou garder que les true et virer celles pas cochées)
(penser à faire un bouton pour tout vider)

Oui évidemment, une modal/popup pour les explications et que le minimum en label sinon ça sera illisible
